[package]
name = "pulse"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
iso8601 = "0.6.2"
reqwest = { version = "0.12.15", features = ["blocking"] }
serde = {version = "1.0.219", features = ["derive"]}
serde_alias = "0.0.2"
serde_json = "1.0.140"
tabled = "0.18.0"
